force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentPlan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentPlanTriggerHandler.cls
public class PaymentPlanTriggerHandler {

	public static final String APPROVAL_BLOCK_MSG = 'You cannot create, modify or delete this record because the related Opportunity is locked for approval.';

    // test coverage provided in CreditorOpportunityTriggerHandlerTest
	public static void blockDMLWhileRelatedOppIsLocked(List<PaymentPlan__c> ppList) {
		
		for (PaymentPlan__c pp : ppList) {
			if (String.isNotBlank(pp.Opportunity__c) && Approval.isLocked(pp.Opportunity__c)) {
				pp.addError(APPROVAL_BLOCK_MSG);
			}
		}
	}
}