force-app/main/default/objects/CreditorOpportunity__c/CreditorOpportunity__c.object-meta.xml
<CustomObject>
    <label>Creditors List</label>
    <nameField>
        <label>Creditor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creditors List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditorOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CreditorOpportunitys</relationshipLabel>
    <relationshipName>CreditorOpportunitys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreditorOpportunityTriggerHandler.cls
public class CreditorOpportunityTriggerHandler {

    public static final String APPROVAL_BLOCK_MSG = 'You cannot create, modify or delete this record because the related Opportunity is locked for approval.';
    
	public static void blockDMLWhileRelatedOppIsLocked(List<CreditorOpportunity__c> coList) {
		
		for (CreditorOpportunity__c co : coList) {
			if (String.isNotBlank(co.Opportunity__c) && Approval.isLocked(co.Opportunity__c)) {
				co.addError(APPROVAL_BLOCK_MSG);
			}
		}
	}
}