force-app/main/default/objects/Account/fields/Account_Holder_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Last_Name__c</fullName>
    <label>Account Holder Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Name__c</fullName>
    <label>Account Holder First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Acct_Phone__c.field-meta.xml
<CustomField>
    <fullName>Acct_Phone__c</fullName>
    <label>Acct Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Acct_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Acct_Street_Address__c</fullName>
    <label>Acct Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_Cardholder_Sequence__c.field-meta.xml
<CustomField>
    <fullName>EPPS_Cardholder_Sequence__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>EPPS Cardholder Sequence</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State1__c.field-meta.xml
<CustomField>
    <fullName>State1__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Estimated_Current_Payment__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Current_Payment__c</fullName>
    <label>Estimated Current Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Debt__c</fullName>
    <label>Estimated Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Integrate_with_EPPS__c.field-meta.xml
<CustomField>
    <fullName>Integrate_with_EPPS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary field to have greater control of Opportunities and downstream objects that are integrated with EPPS</description>
    <inlineHelpText>Temporary field to have greater control of Opportunities and downstream objects that are integrated with EPPS</inlineHelpText>
    <label>Integrate with EPPS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityUpdate__e/OpportunityUpdate__e.object-meta.xml
<CustomObject>
    <label>OpportunityUpdate</label>
    <pluralLabel>OpportunityUpdates</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpportunityUpdate__e/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>OpportunityId</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityUpdate__e/fields/Payment_Draft_Invalidated__c.field-meta.xml
<CustomField>
    <fullName>Payment_Draft_Invalidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flags as true if at least one payment draft was invalidated. This is used in the LWC to fire persistent toast to end user.</description>
    <label>Payment Draft Invalidated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityUpdate__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/PaymentDraft__c.object-meta.xml
<CustomObject>
    <label>Payment Draft</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Payment Draft Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Drafts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentDraft__c/fields/Estimated_Current_Payment__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Current_Payment__c</fullName>
    <description>The estimated current monthly payment amount at the time of draft creation</description>
    <label>Estimated Current Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/fields/Estimated_Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Total_Debt__c</fullName>
    <description>Total debt amount from payment calculator</description>
    <label>Estimated Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/fields/Invalidated_Date__c.field-meta.xml
<CustomField>
    <fullName>Invalidated_Date__c</fullName>
    <description>Date Payment Draft was invalidated</description>
    <inlineHelpText>Date Payment Draft was invalidated</inlineHelpText>
    <label>Invalidated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this payment draft is active. Inactive drafts are preserved for historical reference instead of being deleted.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates the primary draft for the parent record. Only one primary is allowed per parent.</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Drafts</relationshipLabel>
    <relationshipName>Payment_Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentDraft__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Sync</fullName>
                <default>true</default>
                <label>In Sync</label>
            </value>
            <value>
                <fullName>Out of Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : OpportunityTriggerHandler
 * Author          : Shell Black (Scott Fawcett)
 * Created Date    : Jan 27, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 27, 2026
 * Description     : This class is the handler class for the Opportunity trigger
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 27, 2026  │ Scott Fawcett │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
public class OpportunityTriggerHandler {

	public static final String PAYMENT_DRAFT_SYNC_STATUS_OUT_OF_SYNC = 'Out of Sync';
	public static final String OPP_STAGE_SIGNED = 'Contract Signed';

	public static void checkOppMovingToSignatureStage(List<Opportunity> oppList, Map<Id, Opportunity> oldMap) {

		// gather Ids of Opps moving to Signature Stage
		List<Opportunity> oppSignedList = new List<Opportunity>();
		List<Id> accountIds = new List<Id>();
		for (Opportunity opp : oppList) {
			if (String.isNotBlank(opp.StageName) && opp.StageName == OPP_STAGE_SIGNED
				&& opp.StageName != oldMap.get(opp.Id).StageName) {
					
				oppSignedList.add(opp);
				accountIds.add(opp.AccountId);
			}
		}

		//  Get a list of accounts related to the optys		
		Map<Id, Account> theAccountMap = new Map<Id, Account>([SELECT Id, Account_Holder_Name__c, Account_Holder_Last_Name__c,
											Acct_Street_Address__c, City__c, State1__c, Zip_Code__c, EPPS_ID__c,
											Acct_Phone__c, Email__c, Date_of_Birth__c, EPPS_Cardholder_Sequence__c,
											BillingStreet, BillingState, BillingCity, BillingPostalCode
											FROM Account WHERE Id IN: accountIds]);

		if (!oppList.isEmpty()) {
			 PaymentPlanService.buildPaymentScheduleItems(oppSignedList);

			//  If it is moving to signed, we need to add a cardholder to EPPS.
			//  Build AddCardHolder Wrappers for each Opty moving to signed for any account that is not established in EPPS.
			List<EPPSHelperMethods.Cardholder_Wrapper> theCardholderWrappers = new	List<EPPSHelperMethods.Cardholder_Wrapper>();
			for (Opportunity opt: oppSignedList) {
				
				// temporary condition, we only want to send if the opp is marked as Integrate to EPPS
				if (opt.Integrate_with_EPPS__c) {
					Account theAccount = theAccountMap.get(opt.AccountId);
				
					if (String.isBlank(theAccount.EPPS_ID__c)) {
						EPPSHelperMethods.Cardholder_Wrapper theWrapper = new
						EPPSHelperMethods.Cardholder_Wrapper(EPPSHelperMethods.EPPSOperation.EPPS_ADD_CARDHOLDER,
															theAccount.Id,
															theAccount.EPPS_Cardholder_Sequence__c,
															theAccount.Account_Holder_Name__c,
															theAccount.Account_Holder_Last_Name__c,
															theAccount.BillingStreet,
															theAccount.BillingCity,
															theAccount.BillingState,
															theAccount.BillingPostalCode,
															theAccount.Acct_Phone__c,
															theAccount.Email__c);
				
						theCardholderWrappers.add(theWrapper);		
					}
				}
			}
			if (!theCardholderWrappers.isEmpty()) {
				ChunkCardholderWrappers (theCardholderWrappers);
			}
		}
	}

	public static void triggerPlatformEventForLWC(List<Opportunity> oppList, Map<Id, Opportunity> oldMap) {

		Map<Id, OpportunityUpdate__e> eventsMap = new Map<Id, OpportunityUpdate__e>();
		Set<Id> oppIdsSet = new Set<Id>();

		for (Opportunity opp : oppList) {

			if ((opp.Estimated_Total_Debt__c != oldMap.get(opp.Id).Estimated_Total_Debt__c)
			    || opp.Estimated_Current_Payment__c != oldMap.get(opp.Id).Estimated_Current_Payment__c) {

				oppIdsSet.add(opp.Id);
			}

		}
		if (!oppIdsSet.isEmpty()) {
			// we have at least one Opportunity where Total Debt and/or Estimated Current Payment changed
			List<PaymentDraft__c> pdList = [SELECT Id, Is_Active__c, Is_Primary__c, Sync_Status__c, 
											Invalidated_Date__c, Opportunity__c
											FROM PaymentDraft__c WHERE Opportunity__c IN :oppIdsSet
											AND Invalidated_Date__c = null];

			for (PaymentDraft__c pd : pdList) {
				pd.Is_Active__c = false;
				pd.Is_Primary__c = false;
				pd.Sync_Status__c = PAYMENT_DRAFT_SYNC_STATUS_OUT_OF_SYNC;
				pd.Invalidated_Date__c = Date.today();

				if (!eventsMap.containsKey(pd.Opportunity__c)) {
					// create platform event 
					OpportunityUpdate__e ev = new OpportunityUpdate__e(OpportunityId__c = pd.Opportunity__c, 
																		RecordId__c = pd.Opportunity__c,
																		Payment_Draft_Invalidated__c = true);
					eventsMap.put(pd.Opportunity__c, ev);
				}
			}

			// check if we have any Opportunities where a Payment Draft wasnt found
			for (Id oppId : oppIdsSet) {
				if (!eventsMap.containsKey(oppId)) {
					OpportunityUpdate__e ev = new OpportunityUpdate__e(OpportunityId__c = oppId, 
																		RecordId__c = oppId,
																		Payment_Draft_Invalidated__c = false);
					eventsMap.put(oppId, ev);
				}
			}
	
			update pdList;
			EventBus.publish(eventsMap.values());
		}
	}

	public static void ChunkCardholderWrappers (List<EPPSHelperMethods.Cardholder_Wrapper> theCardholderWrapperList) {
		
		// TODO need to add coverage to support the split to work around gov limits
		if (theCardholderWrapperList.isEmpty() == false) {
			System.enqueueJob(new EPPSManageCardHolderQueueable(theCardholderWrapperList));
		}
		/*if (theCardholderWrapperList.isEmpty() == false) {
			if (theCardholderWrapperList.size() <= 50) {
				System.enqueueJob(new EPPSManageCardHolderQueueable(theCardholderWrapperList));

			} else {

				integer counter = theCardholderWrapperList.size();

				List<EPPSHelperMethods.Cardholder_Wrapper> wrapper0 = new List<EPPSHelperMethods.Cardholder_Wrapper>();
				List<EPPSHelperMethods.Cardholder_Wrapper> wrapper1 = new List<EPPSHelperMethods.Cardholder_Wrapper>();
				List<EPPSHelperMethods.Cardholder_Wrapper> wrapper2 = new List<EPPSHelperMethods.Cardholder_Wrapper>();
				List<EPPSHelperMethods.Cardholder_Wrapper> wrapper3 = new List<EPPSHelperMethods.Cardholder_Wrapper>();
				List<EPPSHelperMethods.Cardholder_Wrapper> wrapper4 = new List<EPPSHelperMethods.Cardholder_Wrapper>();

				for(Integer i = 0; i < counter; i++) {
					
					switch on Math.mod(i,5) {
						when 0{wrapper0.add(theCardholderWrapperList[i]);}
						when 1{wrapper1.add(theCardholderWrapperList[i]);}
						when 2{wrapper2.add(theCardholderWrapperList[i]);}
						when 3{wrapper3.add(theCardholderWrapperList[i]);}	
						when 4{wrapper4.add(theCardholderWrapperList[i]);}	
					}

				}

				System.enqueueJob(new EPPSManageCardHolderQueueable(wrapper0));
				System.enqueueJob(new EPPSManageCardHolderQueueable(wrapper1));
				System.enqueueJob(new EPPSManageCardHolderQueueable(wrapper2));
				System.enqueueJob(new EPPSManageCardHolderQueueable(wrapper3));
				System.enqueueJob(new EPPSManageCardHolderQueueable(wrapper4));
			}
		}*/
	}
}