force-app/main/default/objects/Account/fields/Bank_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Bank_Street_Address__c</fullName>
    <label>Bank Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Settlement_Fee__c/Settlement_Fee__c.object-meta.xml
<CustomObject>
    <label>Settlement Fee</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Settlement Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Fee__c/fields/Settlement_Plan_Item__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan_Item__c</fullName>
    <label>Settlement Plan Item</label>
    <referenceTo>Settlement_Plan_Item__c</referenceTo>
    <relationshipLabel>Settlement Fees</relationshipLabel>
    <relationshipName>Settlement_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banking Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Settlement Fee</fullName>
            </value>
            <value>
                <fullName>SettlementPayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Draft__c/Settlement_Plan_Draft__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan</label>
    <nameField>
        <label>Settlement Plan Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settlement Plan Draft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Item__c/Settlement_Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan Item</label>
    <nameField>
        <displayFormat>SPI-{00000000}</displayFormat>
        <label>Settlement Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Item__c/fields/Settlement_Plan__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan__c</fullName>
    <label>Settlement Plan</label>
    <referenceTo>Settlement_Plan_Draft__c</referenceTo>
    <relationshipLabel>Settlement Plan Items</relationshipLabel>
    <relationshipName>Settlement_Plan_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Immediate Processing</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EPPSSettlementFeeStatusBatch.cls
public class EPPSSettlementFeeStatusBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable 
{
	//  This is the method required for this batch to be scheduable.
    public void execute(SchedulableContext sc) 
	{       
												//  Change this to metadata record setting for EPPSSettlementFeeStatusBatch size
		Database.executeBatch(new EPPSSettlementFeeStatusBatch(), 5);
	}


    public Database.QueryLocator start(Database.BatchableContext bc) {

        Date targetDate = EPPSHelperMethods.getDateAfterBusinessDays(2);

        return Database.getQueryLocator([SELECT Id,
										Amount__c,
										Fee_Id__c,
										Name,
										Status_Code__c,
										Transaction_Id__c,
										Type__c,
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c,		
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c,
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c,
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name,
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c,
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c,
										Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c
										FROM Settlement_Fee__c
										WHERE Settlement_Plan_Item__r.Status__c = 'Processing'              
										//AND Payment_Plan__r.Status__c = 'Active'  ************ TODO!
									]);
    }

	//  Method executed per batch of records.
    public void execute(Database.BatchableContext bc, List<Settlement_Fee__c> scope) 
	{
		//  3 Callouts per record for each field containing a transaction ID.
		//  Payment_Amount_Eft_Transaction_Id__c, Bank_Fee_EFT_Transaction_Id__c, Commission_Fee_EFT_Transaction_Id__c
		//  Max callouts per execution 100.  Number of records per batch cannot exceed 100/number of fields to query on.
		//  Max Batch of 33 records

		//  Loop through the records, 1 callout per field
		//  Callout skipped if the FEE ID is blank/null
		for (Settlement_Fee__c item : scope)
		{		
			item =  CalloutAndPopulateFields(item);			
		}

		Database.update(scope);

		IntegrationLogUtil.flush();
	}
	
	public Settlement_Fee__c CalloutAndPopulateFields(Settlement_Fee__c item)
	{
		try
		{
			EPPSHelperMethods.FindFee_Wrapper itemWrapper = new	EPPSHelperMethods.FindFee_Wrapper();							

			itemWrapper.FeeID = item.Fee_Id__c;
			
			// Callout to EPPS
			EPPSHelperMethods.EPPSResponse response = EPPSIntegrationMethodsEnhanced.findFeeById(itemWrapper);

			if (response.success) 
			{			
				EPPSHelperMethods.FindFee_Wrapper wrapper = response.FoundFees.get(item.Fee_Id__c);

				item.Transaction_Id__c = EPPSHelperMethods.safeString(wrapper.EftTransactionID);
				item.Status_Code__c = EPPSHelperMethods.safeString(wrapper.StatusCode);
			
				//item.Status_Date__c = EPPSHelperMethods.safeDate(wrapper.StatusDate);				
				
				IntegrationLogUtil.createLog(
				IntegrationLogUtil.logBuilder()
				.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
				.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
				.method('findFeeById')
				.request(response.SOAPRequestBody)
				.response(response.SOAPResponseBody)
				.httpCode(response.HTTPResponseCode)
				.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
				.build());

				}
				else
				{
					IntegrationLogUtil.createLog(
					IntegrationLogUtil.logBuilder()
					.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
					.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
					.method('findFeeById')
					.request(response.SOAPRequestBody)
					.response(response.SOAPResponseBody)
					.httpCode(response.HTTPResponseCode)
					.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
					.build());
				}
		}
		catch (Exception e)
		{
			IntegrationLogUtil.createLog(
			IntegrationLogUtil.logBuilder()
			.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
			.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
			.method('findFeeById')
			.exceptionMsg(EPPSHelperMethods.getExceptionDetails(e))
			.status(IntegrationLogUtil.LogStatus.Failure)
			.build());
		}
		return item;
	}

    public void finish(Database.BatchableContext bc) 
	{
		//  When it is done, start the 
 												//  Change this to metadata record setting for EPPSSettlementFeeStatusBatch size
		Database.executeBatch(new EPPSPaymentFeeStatusBatch(), 5);   
    }
}