force-app/main/default/objects/Account/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_EPPS_Integration__c.field-meta.xml
<CustomField>
    <fullName>Last_EPPS_Integration__c</fullName>
    <description>Last time EPPS integration was attempted</description>
    <inlineHelpText>Last time EPPS integration was attempted</inlineHelpText>
    <label>Last EPPS Integration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Routing__c.field-meta.xml
<CustomField>
    <fullName>Routing__c</fullName>
    <inlineHelpText>Bank&apos;s Routing Number</inlineHelpText>
    <label>Routing</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Payment_Schedule_Item__c/Payment_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individual payment items in a payment schedule</description>
    <label>Payment Schedule Item</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Payment Schedule Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Bank2_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bank2_Fee_Amount__c</fullName>
    <label>Bank 2 Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

deactivate-pages/objects/objects/Payment_Schedule_Item__c/fields/EPPS_EFT_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>EPPS_EFT_Transaction_Id__c</fullName>
    <label>EPPS EFT Transaction Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Last_EPPS_Integration__c.field-meta.xml
<CustomField>
    <fullName>Last_EPPS_Integration__c</fullName>
    <label>Last EPPS Integration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <description>Parent payment plan for this schedule item</description>
    <label>Payment Plan</label>
    <referenceTo>PaymentPlan__c</referenceTo>
    <relationshipLabel>Payment Schedule Items</relationshipLabel>
    <relationshipName>Payment_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Transmitted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Failed to EPPS</fullName>
            </value>
            <value>
                <fullName>Sent to EPPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <label>Total Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentPlan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentPlan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>SUSPENDED</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Pending_Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EPPSClientPaymentBatch.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : EPPSClientPaymentBatch
 * Author          : Shell Black (Scot Fawcett)
 * Created Date    : Jan 27, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 27, 2026
 * Description     : This class is a batch apex class to find Payment Schedule Items
 *					 that need to be integrated with EPPS.
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 27, 2026  │ Scott Fawcett │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
 public class EPPSClientPaymentBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable {
   
    public void execute(SchedulableContext sc) {

		Map<String, Object> settings = IntegrationLogUtil.getMetadataFieldValues(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT);
		Integer batchSize = Integer.valueOf(settings.get('Batch_Size_for_Client_Payment_Batch__c'));
		Database.executeBatch(new EPPSClientPaymentBatch(), batchSize);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {

        Date targetDate = EPPSHelperMethods.getDateAfterBusinessDays(2);

        return Database.getQueryLocator([
            SELECT Id, Payment_Date__c, Total_Payment__c, Bank2_Fee_Amount__c,
				   Payment_Plan__r.Opportunity__r.AccountId,
				   Payment_Plan__r.Opportunity__r.Account.EPPS_ID__c,
				   Payment_Plan__r.Opportunity__r.Account.Routing__c,
				   Payment_Plan__r.Opportunity__r.Account.Bank_Account__c,
				   Payment_Plan__r.Opportunity__r.Account.Bank_Account_Type__c
            	
            FROM Payment_Schedule_Item__c
            WHERE Status__c = :EPPSHelperMethods.PAYMENT_SCHEDULE_ITEM_STATUS_SCHEDULED
              AND Payment_Date__c = :targetDate
			  AND Payment_Plan__r.Status__c =: EPPSHelperMethods.PAYMENT_PLAN_STATUS_ACTIVE
			  AND Payment_Plan__r.Opportunity__r.Integrate_with_EPPS__c = true // temporary control to limit API interactions with EPPS
        ]); 
    }

    public void execute(Database.BatchableContext bc, List<Payment_Schedule_Item__c> scope) {

        List<Payment_Schedule_Item__c> psiUpdates = new List<Payment_Schedule_Item__c>();

		Set<Id> accountIds = new Set<Id>();
		
        for (Payment_Schedule_Item__c psi : scope) {

			// TODO add check that the relevant bank details are on the account
			// TODO check that the account has an EPPS ID

			try {

				EPPSHelperMethods.EFT_Wrapper wrapper = new EPPSHelperMethods.EFT_Wrapper(
				psi.Payment_Plan__r.Opportunity__r.Account.EPPS_ID__c,
				DateTime.newInstance(psi.Payment_Date__c,Time.newInstance(0,0,0,0)),
				psi.Total_Payment__c,
				psi.Bank2_Fee_Amount__c,
				psi.Payment_Plan__r.Opportunity__r.Account.Bank_Account__c,
				psi.Payment_Plan__r.Opportunity__r.Account.Routing__c,
				psi.Payment_Plan__r.Opportunity__r.Account.Bank_Account_Type__c,
				'',
				'');
					
				EPPSHelperMethods.EPPSResponse res = EPPSIntegrationMethodsEnhanced.AddEFT(wrapper);
                
				IntegrationLogUtil.createLog(IntegrationLogUtil.logBuilder()
					                            .settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
                        						.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
					                            .record(psi.Id)
					                            .method('AddEFT')
					                            .request(res.SOAPRequestBody)
					                            .response(res.SOAPResponseBody)
					                            .httpCode(res.HTTPResponseCode)
                                                .exceptionMsg(res.LastError)
					                            .status(res.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
					                            .build());

				// update PSI record with data from 
				if (res.Success) {
					psiUpdates.add(new Payment_Schedule_Item__c(Id = psi.Id, Last_EPPS_Integration__c = Datetime.now(),
									EPPS_EFT_Transaction_Id__c = String.valueOf(res.EftTransactionID), 
									Status__c = EPPSHelperMethods.PSI_STATUS_PROCESSING));
				} else {
					psiUpdates.add(new Payment_Schedule_Item__c(Id = psi.Id, Last_EPPS_Integration__c = Datetime.now(),
									Status__c = EPPSHelperMethods.PSI_STATUS_FAILED_TO_EPPS));
				}
			} catch (Exception e) {

				IntegrationLogUtil.createLog(IntegrationLogUtil.logBuilder()
					                            .settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
                        						.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
					                            .record(psi.Id)
					                            .method('AddEFT')
					                            .request(null)
					                            .response(null)
					                            .httpCode(null)
												.exceptionMsg(EPPSHelperMethods.getExceptionDetails(e))
					                            .status(IntegrationLogUtil.LogStatus.Failure) 
					                            .build());
					
				psiUpdates.add(new Payment_Schedule_Item__c(Id = psi.Id, Last_EPPS_Integration__c = Datetime.now(),
									Status__c = EPPSHelperMethods.PSI_STATUS_FAILED_TO_EPPS));

			}

		}
    
        IntegrationLogUtil.flush();
        
        if (!psiUpdates.isEmpty()) {
            Database.update(psiUpdates);
        }

	}

    public void finish(Database.BatchableContext bc) {

		if (!Test.isRunningTest()) {
			Map<String, Object> settings = IntegrationLogUtil.getMetadataFieldValues(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT);
			Integer batchSize = Integer.valueOf(settings.get('Batch_Size_for_Payment_Fee_Batch__c'));
			Database.executeBatch(new EPPSPaymentFeeBatch(), batchSize);
		}
    }
}