force-app/main/default/objects/Account/fields/Bank_Phone__c.field-meta.xml
<CustomField>
    <fullName>Bank_Phone__c</fullName>
    <label>Bank Phone #</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Bank_Street_Address__c</fullName>
    <label>Bank Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Routing__c.field-meta.xml
<CustomField>
    <fullName>Routing__c</fullName>
    <inlineHelpText>Bank&apos;s Routing Number</inlineHelpText>
    <label>Routing</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Bank_Information__c/Account_Bank_Information__c.object-meta.xml
<CustomObject>
    <label>Account Bank Information</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Account Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Bank Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Bank_Information__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Bank_Information__c/fields/Bank_Phone__c.field-meta.xml
<CustomField>
    <fullName>Bank_Phone__c</fullName>
    <label>Bank Phone #</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account_Bank_Information__c/fields/Bank_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Bank_Street_Address__c</fullName>
    <label>Bank Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Bank_Information__c/fields/Routing__c.field-meta.xml
<CustomField>
    <fullName>Routing__c</fullName>
    <label>Routing</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Bank_Information__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditorOpportunity__c/CreditorOpportunity__c.object-meta.xml
<CustomObject>
    <label>Creditors List</label>
    <nameField>
        <label>Creditor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creditors List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Fee__c/Settlement_Fee__c.object-meta.xml
<CustomObject>
    <label>Settlement Fee</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Settlement Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Fee__c/fields/Settlement_Plan_Item__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan_Item__c</fullName>
    <label>Settlement Plan Item</label>
    <referenceTo>Settlement_Plan_Item__c</referenceTo>
    <relationshipLabel>Settlement Fees</relationshipLabel>
    <relationshipName>Settlement_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banking Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Settlement Fee</fullName>
            </value>
            <value>
                <fullName>SettlementPayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Draft__c/Settlement_Plan_Draft__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan</label>
    <nameField>
        <label>Settlement Plan Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settlement Plan Draft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Draft__c/fields/CreditorOpportunity__c.field-meta.xml
<CustomField>
    <fullName>CreditorOpportunity__c</fullName>
    <label>CreditorOpportunity</label>
    <referenceTo>CreditorOpportunity__c</referenceTo>
    <relationshipLabel>Settlement Plan Draft</relationshipLabel>
    <relationshipName>Settlement_Plan_Draft</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Draft__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Item__c/Settlement_Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan Item</label>
    <nameField>
        <displayFormat>SPI-{00000000}</displayFormat>
        <label>Settlement Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Item__c/fields/Settlement_Plan__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan__c</fullName>
    <label>Settlement Plan</label>
    <referenceTo>Settlement_Plan_Draft__c</referenceTo>
    <relationshipLabel>Settlement Plan Items</relationshipLabel>
    <relationshipName>Settlement_Plan_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Immediate Processing</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EPPSSettlementFeeBatch.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : EPPSSettlementFeeBatch
 * Author          : Shell Black (Scott Fawcett)
 * Created Date    : Jan 27, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 27, 2026
 * Description     : Batch Class to Process Settlement Fees
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 27, 2026  │ Scott Fawcett │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
public class EPPSSettlementFeeBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable {

    public void execute(SchedulableContext sc) {
	Map<String, Object> settings = IntegrationLogUtil.getMetadataFieldValues(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT);
        Integer batchSize = Integer.valueOf(settings.get('Batch_Size_for_Settlement_Fee_Batch__c'));
         Database.executeBatch(new EPPSSettlementFeeBatch(), batchSize);
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {

		Date targetDate = Date.today();

        return Database.getQueryLocator([
            SELECT Id, Payment_Date__c,
            Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__c,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Routing__c,
            Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c	,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Name,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Phone__c,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c,
			Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c,
			Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name,
			(SELECT Id, Amount__c, Type__c, Fee_Id__c, Status_Code__c
			 FROM Settlement_Fees__r WHERE Type__c != null)
            FROM Settlement_Plan_Item__c
            WHERE Status__c =: EPPSHelperMethods.SETTLEMENT_PLAN_ITEM_STATUS_SCHEDULED
              AND Payment_Date__c = :targetDate
			 AND Settlement_Plan__r.Status__c =: EPPSHelperMethods.SETTLEMENT_PLAN_STATUS_ACTIVE
			 AND Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Integrate_with_EPPS__c = true // temporary control to limit API interactions with EPPS
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Settlement_Plan_Item__c> scope) {

        List<Settlement_Plan_Item__c> spiUpdates = new List<Settlement_Plan_Item__c>();
		List<Settlement_Fee__c> sfUpdates = new List<Settlement_Fee__c>();

		Map<Id, List<EPPSSettlementFeeBatchHelper.AddFee2Wrapper>> spiWrapper = EPPSSettlementFeeBatchHelper.buildAPICallMap(scope);

		for (Id spiId : spiWrapper.keySet()) {

			Settlement_Plan_Item__c spiUpdate = new Settlement_Plan_Item__c(Id = spiId, 
												Status__c = EPPSHelperMethods.SETTLEMENT_PLAN_ITEM_STATUS_PROCESSING);

			for (EPPSSettlementFeeBatchHelper.AddFee2Wrapper wrapper : spiWrapper.get(spiId)) {		

				try {
					EPPSHelperMethods.EPPSResponse resp = EPPSIntegrationMethodsEnhanced.addFee2(wrapper.feeWrapper);

					IntegrationLogUtil.createLog(IntegrationLogUtil.logBuilder()
					                             .settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
                        						 .objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
					                             .record(wrapper.feeSettlementId)
					                             .method('AddFee2')
					                             .request(resp.SOAPRequestBody)
					                             .response(resp.SOAPResponseBody)
					                             .httpCode(resp.HTTPResponseCode)
                                                 .exceptionMsg(resp.LastError)
					                             .status(resp.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
					                             .build());
		
					Settlement_Fee__c thisFSD = new Settlement_Fee__c(Id = wrapper.feeSettlementId);
					
					if (String.isNotBlank(resp.FeeID)) {
						thisFSD.Fee_Id__c = resp.FeeID;
					}

					thisFSD.Status_Code__c = resp.Success ? 'Sent to EPPS' : 'Failed to EPPS';

					sfUpdates.add(thisFSD);

				} catch (Exception e) {
					IntegrationLogUtil.createLog(IntegrationLogUtil.logBuilder()
					                             .settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
                        						 .objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
					                             .record(wrapper.feeSettlementId)
					                             .method('AddFee2')
					                             .request(null)
					                             .response(null)
					                             .httpCode(null)
												 .exceptionMsg(EPPSHelperMethods.getExceptionDetails(e))
					                             .status(IntegrationLogUtil.LogStatus.Failure) 
					                             .build());
					
					sfUpdates.add(new Settlement_Fee__c(Id = wrapper.feeSettlementId, Status_Code__c = 'Failed to EPPS'));
				}
			}
			spiUpdates.add(spiUpdate);
		}
        
        IntegrationLogUtil.flush();
        
        if (!spiUpdates.isEmpty()) {
            Database.update(spiUpdates);
        }

		if (!sfUpdates.isEmpty()) {
			Database.update(sfUpdates);
		}
    }

    public void finish(Database.BatchableContext bc) {
        // Optional: Send summary email or future retry logic
    }
}