force-app/main/default/objects/Account/fields/Bank_Phone__c.field-meta.xml
<CustomField>
    <fullName>Bank_Phone__c</fullName>
    <label>Bank Phone #</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Bank_Street_Address__c</fullName>
    <label>Bank Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Routing__c.field-meta.xml
<CustomField>
    <fullName>Routing__c</fullName>
    <inlineHelpText>Bank&apos;s Routing Number</inlineHelpText>
    <label>Routing</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/CreditorOpportunity__c/CreditorOpportunity__c.object-meta.xml
<CustomObject>
    <label>Creditors List</label>
    <nameField>
        <label>Creditor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creditors List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EPPS_Fee__mdt/EPPS_Fee__mdt.object-meta.xml
<CustomObject>
    <description>Used with addFee API call to determine which fields to be sent and other details</description>
    <label>EPPS Fee</label>
    <pluralLabel>EPPS Fees</pluralLabel>
</CustomObject>

force-app/main/default/objects/EPPS_Fee__mdt/fields/Fee_Description__c.field-meta.xml
<CustomField>
    <fullName>Fee_Description__c</fullName>
    <description>Value to be specified in Description field for addFee</description>
    <inlineHelpText>Value to be specified in Description field for addFee</inlineHelpText>
    <label>Fee Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EPPS_Fee__mdt/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <description>Value to be specified in FeeType field for addFee</description>
    <inlineHelpText>Value to be specified in FeeType field for addFee</inlineHelpText>
    <label>Fee Type</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EPPS_Fee__mdt/fields/Is_Settlement__c.field-meta.xml
<CustomField>
    <fullName>Is_Settlement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When marked as true, additional fields will be sent as part of addFee</description>
    <inlineHelpText>When marked as true, additional fields will be sent as part of addFee</inlineHelpText>
    <label>Is Settlement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/Settlement_Fee__c.object-meta.xml
<CustomObject>
    <label>Settlement Fee</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Settlement Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Fee__c/fields/Settlement_Plan_Item__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan_Item__c</fullName>
    <label>Settlement Plan Item</label>
    <referenceTo>Settlement_Plan_Item__c</referenceTo>
    <relationshipLabel>Settlement Fees</relationshipLabel>
    <relationshipName>Settlement_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banking Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Settlement Fee</fullName>
            </value>
            <value>
                <fullName>SettlementPayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Draft__c/Settlement_Plan_Draft__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan</label>
    <nameField>
        <label>Settlement Plan Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settlement Plan Draft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Draft__c/fields/CreditorOpportunity__c.field-meta.xml
<CustomField>
    <fullName>CreditorOpportunity__c</fullName>
    <label>CreditorOpportunity</label>
    <referenceTo>CreditorOpportunity__c</referenceTo>
    <relationshipLabel>Settlement Plan Draft</relationshipLabel>
    <relationshipName>Settlement_Plan_Draft</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Item__c/Settlement_Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan Item</label>
    <nameField>
        <displayFormat>SPI-{00000000}</displayFormat>
        <label>Settlement Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Item__c/fields/Settlement_Plan__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan__c</fullName>
    <label>Settlement Plan</label>
    <referenceTo>Settlement_Plan_Draft__c</referenceTo>
    <relationshipLabel>Settlement Plan Items</relationshipLabel>
    <relationshipName>Settlement_Plan_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EPPSSettlementFeeBatchHelper.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : EPPSSettlementFeeBatchHelper
 * Author          : Shell Black (Scott Fawcett)
 * Created Date    : Jan 27, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 27, 2026
 * Description     : Helper Class to support EPPSSettlementFeeBatch
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 27, 2026  │ Scott Fawcett │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
public class EPPSSettlementFeeBatchHelper {

	public static Map<Id, List<AddFee2Wrapper>> buildAPICallMap(List<Settlement_Plan_Item__c> spiList) {

		Map<Id, List<AddFee2Wrapper>> returnMap = new Map<Id, List<AddFee2Wrapper>> ();
		Map<String, EPPS_Fee__mdt> feeMap = EPPSHelperMethods.getFeesByLabel();

		for (Settlement_Plan_Item__c spi : spiList) {

			List<AddFee2Wrapper> addWrapperList = new List<AddFee2Wrapper>();

			// loop through child fee/settlement records
			for (Settlement_Fee__c sf : spi.Settlement_Fees__r) {

				AddFee2Wrapper addWrapper = new AddFee2Wrapper();
				// TODO what if the metadata is missing for a fee type? or fee type not specified, maybe trap null at query
				
				// this fee type details
				EPPS_Fee__mdt feeDetails = feeMap.get(sf.Type__c);

				EPPSHelperMethods.Fee_Wrapper fee = new EPPSHelperMethods.Fee_Wrapper();

				fee.CardHolderID = spi.Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c;	
				fee.FeeDate = DateTime.newInstance(spi.Payment_Date__c, Time.newInstance(0, 0, 0, 0));
				fee.FeeAmount = sf.Amount__c;
				fee.FeeType = feeDetails.Fee_Type__c;

				fee.Description = feeDetails.Fee_Description__c;

				if (feeDetails.Is_Settlement__c) {

					//TODO make sure this data is there
					fee.AccountNumber = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c;
					fee.RoutingNumber = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Routing__c;
					fee.PaidToName = spi.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name;
					fee.PaidToPhone = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Phone__c;
					fee.PaidToStreet = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c;
					//fee.PaidToStreet2 = 'Test'; -- Optional
					fee.PaidToCity = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c;
					fee.PaidToState = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c;
					fee.PaidToZip = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c;
					fee.ContactName = spi.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name;
					fee.PaidToCustomerNumber = spi.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c;
				}

				addWrapper.feeWrapper = fee;
				addWrapper.feeSettlementId = sf.Id;
				addWrapperList.add(addWrapper);
			}

			returnMap.put(spi.Id, addWrapperList);
		}
		return returnMap;
	}

	public class AddFee2Wrapper {

		public EPPSHelperMethods.Fee_Wrapper feeWrapper;
		public String feeIdField;
		public String statusField;
		public Id feeSettlementId;
	}
}