force-app/main/default/objects/Account/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Bank_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Bank_Street_Address__c</fullName>
    <label>Bank Street Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Routing__c.field-meta.xml
<CustomField>
    <fullName>Routing__c</fullName>
    <inlineHelpText>Bank&apos;s Routing Number</inlineHelpText>
    <label>Routing</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/CreditorOpportunity__c/CreditorOpportunity__c.object-meta.xml
<CustomObject>
    <label>Creditors List</label>
    <nameField>
        <label>Creditor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creditors List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Fee__c/Payment_Fee__c.object-meta.xml
<CustomObject>
    <description>Payment fees associated with Payment Schedule Items</description>
    <label>Payment Fee</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Payment Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Fee__c/fields/Fee_Id__c.field-meta.xml
<CustomField>
    <fullName>Fee_Id__c</fullName>
    <label>Fee Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Payment_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Item__c</fullName>
    <label>Payment Schedule Item</label>
    <referenceTo>Payment_Schedule_Item__c</referenceTo>
    <relationshipLabel>Payment Fees</relationshipLabel>
    <relationshipName>Payment_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/Payment_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individual payment items in a payment schedule</description>
    <label>Payment Schedule Item</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Payment Schedule Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <description>Parent payment plan for this schedule item</description>
    <label>Payment Plan</label>
    <referenceTo>PaymentPlan__c</referenceTo>
    <relationshipLabel>Payment Schedule Items</relationshipLabel>
    <relationshipName>Payment_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentPlan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/Settlement_Fee__c.object-meta.xml
<CustomObject>
    <label>Settlement Fee</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Settlement Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Fee__c/fields/Settlement_Plan_Item__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan_Item__c</fullName>
    <label>Settlement Plan Item</label>
    <referenceTo>Settlement_Plan_Item__c</referenceTo>
    <relationshipLabel>Settlement Fees</relationshipLabel>
    <relationshipName>Settlement_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Settlement_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banking Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Settlement Fee</fullName>
            </value>
            <value>
                <fullName>SettlementPayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Draft__c/Settlement_Plan_Draft__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan</label>
    <nameField>
        <label>Settlement Plan Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settlement Plan Draft</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Draft__c/fields/CreditorOpportunity__c.field-meta.xml
<CustomField>
    <fullName>CreditorOpportunity__c</fullName>
    <label>CreditorOpportunity</label>
    <referenceTo>CreditorOpportunity__c</referenceTo>
    <relationshipLabel>Settlement Plan Draft</relationshipLabel>
    <relationshipName>Settlement_Plan_Draft</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Settlement_Plan_Item__c/Settlement_Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Settlement Plan Item</label>
    <nameField>
        <displayFormat>SPI-{00000000}</displayFormat>
        <label>Settlement Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Settlement_Plan_Item__c/fields/Settlement_Plan__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Plan__c</fullName>
    <label>Settlement Plan</label>
    <referenceTo>Settlement_Plan_Draft__c</referenceTo>
    <relationshipLabel>Settlement Plan Items</relationshipLabel>
    <relationshipName>Settlement_Plan_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Banking Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Program Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Setup Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Payee Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Wire Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Wire Received Fee</fullName>
    </customValue>
    <description>Types of payment fees for Payment_Fee__c records</description>
    <masterLabel>Payment Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EPPSManageFees.cls
public class EPPSManageFees  
{


	//////////////////   Update Settlement Section

	//  Accepts a Settlement Plan Item and updates all line item detail records for 
	//  that line item.
	@AuraEnabled
	public static List<EPPSHelperMethods.EPPSResponse> updateSettlementLineItemFees(ID theItemId)
	{
		List<Settlement_Fee__c> theDetailItems = new List<Settlement_Fee__c>();

		theDetailItems = getFeeSettlementDetailRecords(theItemId, theDetailItems);
		List<EPPSHelperMethods.EPPSResponse> theResponses = new List<EPPSHelperMethods.EPPSResponse>();
		for (Settlement_Fee__c theDetailItem : theDetailItems)
		{
			EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
			wrapper = convertSettlementFeeItemToFeeWrapper(theDetailItem);
			wrapper.FeeID = theDetailItem.Fee_Id__c;
			wrapper.FeeAmount = theDetailItem.Amount__c;
			
			EPPSHelperMethods.EPPSResponse theResponse = updateFee(wrapper, theDetailItem.Id);	
					
			theDetailItem.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';
			theResponses.add(theResponse);
		}

		update theDetailItems;
		return theResponses;
	}

	//  Accepts a detail Item Id and updates a singular fee.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse updateSettlementDetailFee(ID theDetailItemId)
	{
		Settlement_Fee__c theDetailItem = new Settlement_Fee__c(); 
		theDetailItem = getSettlementPlanDetailRecord(theDetailItemId, theDetailItem);

		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertSettlementFeeItemToFeeWrapper(theDetailItem);
		wrapper.FeeID = theDetailItem.Fee_Id__c;
		wrapper.FeeAmount = theDetailItem.Amount__c;
		
		EPPSHelperMethods.EPPSResponse theResponse = updateFee(wrapper, theDetailItemId);	
					
		theDetailItem.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';
							
		return theResponse;
	}


	//  Accepts a settlement plan item ID and a string value for the fee type to be updated.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse updateSettlementDetailFeeByType(ID theItemId, string theType)
	{
		Settlement_Fee__c theSettlementDetail = new Settlement_Fee__c();

		theSettlementDetail = getFeeSettlementDetailRecordByType(theItemId, theSettlementDetail, theType);
		
		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertSettlementFeeItemToFeeWrapper(theSettlementDetail);
		wrapper.FeeID = theSettlementDetail.Fee_Id__c;
		wrapper.FeeAmount = theSettlementDetail.Amount__c;
			
		EPPSHelperMethods.EPPSResponse theResponse = updateFee(wrapper, theSettlementDetail.Id);	
					
		theSettlementDetail.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';	
							
		return theResponse;
	}


	//////////////////   Update Payment Section


	//  Accepts a Payment Plan Item and updates all line item detail records for 
	//  that line item.
	@AuraEnabled
	public static List<EPPSHelperMethods.EPPSResponse> updatePaymentLineItemFees(ID theItemId)
	{
		List<Payment_Fee__c> theDetailItems = new List<Payment_Fee__c>();		

		theDetailItems = getFeePaymentDetailRecords(theItemId, theDetailItems);
		List<EPPSHelperMethods.EPPSResponse> theResponses = new List<EPPSHelperMethods.EPPSResponse>();
		for (Payment_Fee__c theDetailItem : theDetailItems)
		{
			EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
			wrapper = convertPaymentItemToFeeWrapper(theDetailItem);
			wrapper.FeeID = theDetailItem.Fee_Id__c;
			wrapper.FeeAmount = theDetailItem.Amount__c;
			
			EPPSHelperMethods.EPPSResponse theResponse = updateFee(wrapper, theDetailItem.Id);	
					
			theDetailItem.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';
			theResponses.add(theResponse);
		}

		update theDetailItems;
		return theResponses;
	}


	//  Accepts a Payment detail Item Id and updates a singular fee.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse updatePaymentDetailFee(ID theDetailItemId)
	{
		Payment_Fee__c theDetailItem = new Payment_Fee__c(); 
		theDetailItem = getPaymentDetailRecord(theDetailItemId, theDetailItem);

		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertPaymentItemToFeeWrapper(theDetailItem);
		wrapper.FeeID = theDetailItem.Fee_Id__c;
		wrapper.FeeAmount = theDetailItem.Amount__c;
		
		EPPSHelperMethods.EPPSResponse theResponse = updateFee(wrapper, theDetailItemId);	
					
		theDetailItem.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';
							
		return theResponse;
	}


	//  Accepts a Payment plan item ID and a string value for the fee type to be updated.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse updatePaymentDetailFeeByType(ID theItemId, string theType)
	{
		Payment_Fee__c thePaymentDetail = new Payment_Fee__c();		

		thePaymentDetail = getFeePaymentDetailRecordByType(theItemId, thePaymentDetail, theType);
		
		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertPaymentItemToFeeWrapper(thePaymentDetail);
		wrapper.FeeID = thePaymentDetail.Fee_Id__c;
		wrapper.FeeAmount = thePaymentDetail.Amount__c;
			
		EPPSHelperMethods.EPPSResponse theResponse = updateFee(wrapper, thePaymentDetail.Id);	
					
		thePaymentDetail.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';	
							
		return theResponse;
	}


    public static EPPSHelperMethods.EPPSResponse updateFee(EPPSHelperMethods.Fee_Wrapper wrapper, Id recordId) 
	{        
		EPPSHelperMethods.EPPSResponse response = EPPSIntegrationMethodsEnhanced.updateFee2(wrapper);
		try
		{			
			if (response.success) 
			{
				IntegrationLogUtil.createLog(
				IntegrationLogUtil.logBuilder()
				.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
				.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
				.record(recordId)
				.method('updateFee')
				.request(response.SOAPRequestBody)
				.response(response.SOAPResponseBody)
				.httpCode(response.HTTPResponseCode)
				.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
				.build());
				IntegrationLogUtil.flush();
				return response;
			}
			else
			{
				IntegrationLogUtil.createLog(
				IntegrationLogUtil.logBuilder()
				.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
				.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
				.record(recordId)
				.method('updateFee')
				.request(response.SOAPRequestBody)
				.response(response.SOAPResponseBody)
				.httpCode(response.HTTPResponseCode)
				.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
				.build());
				IntegrationLogUtil.flush();
				return response;
			}
		}
		catch (Exception e)
		{
			IntegrationLogUtil.createLog(
			IntegrationLogUtil.logBuilder()
			.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
			.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
			.record(recordId)
			.method('updateFee')
			.exceptionMsg(EPPSHelperMethods.getExceptionDetails(e))
			.status(IntegrationLogUtil.LogStatus.Failure)
			.build());
			IntegrationLogUtil.flush();
			return response;
		}
    }


	//////////////////   Void Settlement Section

	@AuraEnabled
	public static List<EPPSHelperMethods.EPPSResponse> voidSettlementLineItemFees(ID theItemId)
	{
		List<Settlement_Fee__c> theSettlementDetails = new List<Settlement_Fee__c>();

		theSettlementDetails = getFeeSettlementDetailRecords(theItemId, theSettlementDetails);

		List<EPPSHelperMethods.EPPSResponse> theResponses = new List<EPPSHelperMethods.EPPSResponse>();
		for (Settlement_Fee__c theSettlementDetail : theSettlementDetails)
		{
			EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
			wrapper = convertSettlementFeeItemToFeeWrapper(theSettlementDetail);
			wrapper.FeeID = theSettlementDetail.Fee_Id__c;
			
			EPPSHelperMethods.EPPSResponse theResponse = voidFee(wrapper, theSettlementDetail.Id);			
			theResponses.add(theResponse);
		}

		return theResponses;
	}

	//  Accepts a detail Item Id and updates a singular fee.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse voidSettlementDetailFee(ID theDetailItemId)
	{
		Settlement_Fee__c theDetailItem = new Settlement_Fee__c(); 
		theDetailItem = getSettlementPlanDetailRecord(theDetailItemId, theDetailItem);

		List<EPPSHelperMethods.EPPSResponse> theResponses = new List<EPPSHelperMethods.EPPSResponse>();

		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertSettlementFeeItemToFeeWrapper(theDetailItem);
		wrapper.FeeID = theDetailItem.Fee_Id__c;
		
		EPPSHelperMethods.EPPSResponse theResponse = voidFee(wrapper, theDetailItem.Id);			
		return theResponse;

	}


	//  Accepts a settlement plan item ID and a string value for the fee type to be updated.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse voidSettlementDetailFeeByType(ID theItemId, string theType)
	{
		Settlement_Fee__c theSettlementDetail = new Settlement_Fee__c();

		theSettlementDetail = getFeeSettlementDetailRecordByType(theItemId, theSettlementDetail, theType);
		
		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertSettlementFeeItemToFeeWrapper(theSettlementDetail);
		wrapper.FeeID = theSettlementDetail.Fee_Id__c;
			
		EPPSHelperMethods.EPPSResponse theResponse = voidFee(wrapper, theSettlementDetail.Id);					
		return theResponse;
	}


	//////////////////   Void Payment Section

	//  Accepts a Payment Plan Item and updates all line item detail records for 
	//  that line item.
	@AuraEnabled
	public static List<EPPSHelperMethods.EPPSResponse> voidPaymentFees(ID theItemId)
	{
		List<Payment_Fee__c> theDetailItems = new List<Payment_Fee__c>();		

		theDetailItems = getFeePaymentDetailRecords(theItemId, theDetailItems);
		List<EPPSHelperMethods.EPPSResponse> theResponses = new List<EPPSHelperMethods.EPPSResponse>();
		for (Payment_Fee__c theDetailItem : theDetailItems)
		{
			EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
			wrapper = convertPaymentItemToFeeWrapper(theDetailItem);
			wrapper.FeeID = theDetailItem.Fee_Id__c;
			wrapper.FeeAmount = theDetailItem.Amount__c;
			
			EPPSHelperMethods.EPPSResponse theResponse = voidFee(wrapper, theDetailItem.Id);	
					
			theDetailItem.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';
			theResponses.add(theResponse);
		}

		update theDetailItems;
		return theResponses;
	}


	//  Accepts a Payment detail Item Id and updates a singular fee.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse voidPaymentFee(ID theDetailItemId)
	{
		Payment_Fee__c theDetailItem = new Payment_Fee__c(); 
		theDetailItem = getPaymentDetailRecord(theDetailItemId, theDetailItem);

		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertPaymentItemToFeeWrapper(theDetailItem);
		wrapper.FeeID = theDetailItem.Fee_Id__c;
		wrapper.FeeAmount = theDetailItem.Amount__c;
		
		EPPSHelperMethods.EPPSResponse theResponse = voidFee(wrapper, theDetailItemId);	
					
		theDetailItem.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';
							
		return theResponse;
	}


	//  Accepts a Payment plan item ID and a string value for the fee type to be updated.
	@AuraEnabled
	public static EPPSHelperMethods.EPPSResponse voidPaymentFeeByType(ID theItemId, string theType)
	{
		Payment_Fee__c thePaymentDetail = new Payment_Fee__c();		

		thePaymentDetail = getFeePaymentDetailRecordByType(theItemId, thePaymentDetail, theType);
		
		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
		wrapper = convertPaymentItemToFeeWrapper(thePaymentDetail);
		wrapper.FeeID = thePaymentDetail.Fee_Id__c;
		wrapper.FeeAmount = thePaymentDetail.Amount__c;
			
		EPPSHelperMethods.EPPSResponse theResponse = voidFee(wrapper, thePaymentDetail.Id);	
					
		thePaymentDetail.Status_Code__c = theResponse.Success ? 'Sent to EPPS' : 'Failed to EPPS';	
							
		return theResponse;
	}


    public static EPPSHelperMethods.EPPSResponse voidFee(EPPSHelperMethods.Fee_Wrapper wrapper, Id RecordId) 
	{
		EPPSHelperMethods.EPPSResponse response = EPPSIntegrationMethodsEnhanced.voidFee(wrapper);
		try
		{			
			if (response.success) 
			{
				IntegrationLogUtil.createLog(
				IntegrationLogUtil.logBuilder()
				.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
				.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
				.method('voidFee')
				.record(recordId)
				.request(response.SOAPRequestBody)
				.response(response.SOAPResponseBody)
				.httpCode(response.HTTPResponseCode)
				.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
				.build());
				IntegrationLogUtil.flush();
				return response;
			}
			else
			{
				IntegrationLogUtil.createLog(
				IntegrationLogUtil.logBuilder()
				.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
				.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
				.method('voidFee')
				.record(recordId)
				.request(response.SOAPRequestBody)
				.response(response.SOAPResponseBody)
				.httpCode(response.HTTPResponseCode)
				.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
				.build());
				IntegrationLogUtil.flush();
				return response;
			}
		}
		catch (Exception e)
		{
			IntegrationLogUtil.createLog(
			IntegrationLogUtil.logBuilder()
			.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
			.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
			.method('voidFee')
			.record(recordId)
			.exceptionMsg(EPPSHelperMethods.getExceptionDetails(e))
			.status(IntegrationLogUtil.LogStatus.Failure)
			.build());
			IntegrationLogUtil.flush();
			return response;
		}
    }

	public static EPPSHelperMethods.Fee_Wrapper convertSettlementFeeItemToFeeWrapper(Settlement_Fee__c theItem)
	{
		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();
								
		wrapper.AccountNumber =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c;
		wrapper.CardHolderID =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c;
		wrapper.ContactName =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name;
		wrapper.PaidToCity =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c;
		wrapper.PaidToCustomerNumber =	theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c;
		wrapper.PaidToName =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name;
		wrapper.PaidToState =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c;
		wrapper.PaidToStreet =			theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c;
		wrapper.PaidToZip =				theItem.Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c;		

		return wrapper;
	}

	public static EPPSHelperMethods.Fee_Wrapper convertPaymentItemToFeeWrapper(Payment_Fee__c theItem)
	{
		EPPSHelperMethods.Fee_Wrapper wrapper = new EPPSHelperMethods.Fee_Wrapper();

		wrapper.CardHolderID =			theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.EPPS_ID__c;	
		wrapper.PaidToCustomerNumber =	theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account__c;
		wrapper.AccountNumber =			theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account__c;
		wrapper.PaidToStreet =			theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Street_Address__c;
		wrapper.PaidToCity =			theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.City__c;
		wrapper.PaidToState =			theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.State__c;
		wrapper.PaidToZip =				theItem.Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Zip_Code__c;

		//wrapper.ContactName =			theItem.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name;
		//wrapper.PaidToName =			theItem.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name;

		return wrapper;
	}


	//  Returns all Settlement_Fee__c records related to a Settlement Plan Item
	//  theReocrdID = the Settlement Pan Item Record to get child records for.
	public static List<Settlement_Fee__c> getFeeSettlementDetailRecords(ID theRecordID, List<Settlement_Fee__c> theDetailRecords)
	{
		theDetailRecords = [SELECT Id, Amount__c,
							 Fee_Id__c, Name,
							Status_Code__c,
							Transaction_Id__c,
							Type__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c,		
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c
							FROM Settlement_Fee__c
							WHERE Settlement_Plan_Item__c =: theRecordID];

		return theDetailRecords;
	}

	public static Settlement_Fee__c getFeeSettlementDetailRecordByType(ID theRecordID, Settlement_Fee__c theDetailRecord, string theType)
	{
		theDetailRecord = [SELECT Id,
							Amount__c,
							Fee_Id__c,
							Name,
							Status_Code__c,
							Transaction_Id__c,
							Type__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c,		
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c
							FROM Settlement_Fee__c
							WHERE Settlement_Plan_Item__c =: theRecordID AND Type__C =: theType];

		return theDetailRecord;
	}

	public static Settlement_Fee__c getSettlementPlanDetailRecord(ID theRecordId, Settlement_Fee__c theDetailRecord)
	{
		theDetailRecord = [SELECT Id,
							Amount__c,
							Fee_Id__c,
							Name,
							Status_Code__c,
							Transaction_Id__c,
							Type__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Opportunity__r.Account.EPPS_Id__c,		
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.City__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Account_Number__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Settlement_Contact__r.Name,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.State__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Bank_Street_Address__c,
							Settlement_Plan_Item__r.Settlement_Plan__r.CreditorOpportunity__r.Account_Bank_Information__r.Zip_Code__c
							FROM Settlement_Fee__c
							WHERE Id =: theRecordID];

		return theDetailRecord;
	}

	//  Returns all Fee_Payment_Detail__c records related to a Settlement Plan Item
	//  theReocrdID = the Settlement Pan Item Record to get child records for.
	public static List<Payment_Fee__c> getFeePaymentDetailRecords(ID theRecordID, List<Payment_Fee__c> theDetailRecords)
	{
		theDetailRecords = [SELECT Id,
							Amount__c,
							Fee_Id__c,
							Name,
							Status_Code__c,
							Transaction_Id__c,
							Type__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.AccountId,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.EPPS_ID__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Routing__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account_Type__c 
							FROM Payment_Fee__c
							WHERE Payment_Schedule_Item__c =: theRecordID];

		return theDetailRecords;
	}



	public static Payment_Fee__c getFeePaymentDetailRecordByType(ID theRecordID, Payment_Fee__c theDetailRecord, string theType)
	{
		theDetailRecord = [SELECT Id,
							Amount__c,
							Fee_Id__c,
							Name,
							Status_Code__c,
							Transaction_Id__c,
							Type__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.AccountId,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.EPPS_ID__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Routing__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account_Type__c 
							FROM Payment_Fee__c
							WHERE Payment_Schedule_Item__c =: theRecordID AND Type__C =: theType];

		return theDetailRecord;
	}


	public static Payment_Fee__c getPaymentDetailRecord(ID theRecordId, Payment_Fee__c theDetailRecord)
	{
		theDetailRecord = [SELECT Id,
							Amount__c,
							Fee_Id__c,
							Name,
							Status_Code__c,
							Transaction_Id__c,
							Type__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.AccountId,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.EPPS_ID__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Routing__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account__c,
							Payment_Schedule_Item__r.Payment_Plan__r.Opportunity__r.Account.Bank_Account_Type__c 
							FROM Payment_Fee__c
							WHERE Id =: theRecordID];

		return theDetailRecord;
	}
}