force-app/main/default/objects/Account/fields/EPPS_ID__c.field-meta.xml
<CustomField>
    <fullName>EPPS_ID__c</fullName>
    <label>EPPS ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/EPPS_Fee__mdt/EPPS_Fee__mdt.object-meta.xml
<CustomObject>
    <description>Used with addFee API call to determine which fields to be sent and other details</description>
    <label>EPPS Fee</label>
    <pluralLabel>EPPS Fees</pluralLabel>
</CustomObject>

force-app/main/default/objects/EPPS_Fee__mdt/fields/Fee_Description__c.field-meta.xml
<CustomField>
    <fullName>Fee_Description__c</fullName>
    <description>Value to be specified in Description field for addFee</description>
    <inlineHelpText>Value to be specified in Description field for addFee</inlineHelpText>
    <label>Fee Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EPPS_Fee__mdt/fields/PaidToContactName__c.field-meta.xml
<CustomField>
    <fullName>PaidToContactName__c</fullName>
    <description>Value passed for PaidToContactName when its not for settlement</description>
    <inlineHelpText>Value passed for PaidToContactName when its not for settlement</inlineHelpText>
    <label>PaidToContactName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EPPS_Fee__mdt/fields/PaidToName__c.field-meta.xml
<CustomField>
    <fullName>PaidToName__c</fullName>
    <description>Value passed for PaidToName when its not for settlement</description>
    <inlineHelpText>Value passed for PaidToName when its not for settlement</inlineHelpText>
    <label>PaidToName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EPPS_Fee__mdt/fields/Send_to_EPPS__c.field-meta.xml
<CustomField>
    <fullName>Send_to_EPPS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this fee type should be sent to EPPS, some fees are internally managed and should not be sent.</description>
    <inlineHelpText>If this fee type should be sent to EPPS, some fees are internally managed and should not be sent.</inlineHelpText>
    <label>Send to EPPS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/Payment_Fee__c.object-meta.xml
<CustomObject>
    <description>Payment fees associated with Payment Schedule Items</description>
    <label>Payment Fee</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Payment Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Fee__c/fields/Payment_Schedule_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Item__c</fullName>
    <label>Payment Schedule Item</label>
    <referenceTo>Payment_Schedule_Item__c</referenceTo>
    <relationshipLabel>Payment Fees</relationshipLabel>
    <relationshipName>Payment_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/Payment_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Individual payment items in a payment schedule</description>
    <label>Payment Schedule Item</label>
    <nameField>
        <displayFormat>PSI-{000000}</displayFormat>
        <label>Payment Schedule Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/fee_Description__c.field-meta.xml
<CustomField>
    <fullName>fee_Description__c</fullName>
    <label>fee.Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule_Item__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <description>Parent payment plan for this schedule item</description>
    <label>Payment Plan</label>
    <referenceTo>PaymentPlan__c</referenceTo>
    <relationshipLabel>Payment Schedule Items</relationshipLabel>
    <relationshipName>Payment_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Payment Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentPlan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Banking Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Program Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Setup Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Payee Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Wire Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Wire Received Fee</fullName>
    </customValue>
    <description>Types of payment fees for Payment_Fee__c records</description>
    <masterLabel>Payment Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EPPSPaymentFeeBatchHelper.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : EPPSPaymentFeeBatchHelper
 * Author          : Shell Black (Scott Fawcett)
 * Created Date    : Jan 27, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Jan 27, 2026
 * Description     : Helper class for EPPSPaymentFeeBatch
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 27, 2026  │ Scott Fawcett │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
public class EPPSPaymentFeeBatchHelper {

	public static Map<Id, List<AddFee2Wrapper>> buildAPICallMap(List<Payment_Schedule_Item__c> psiList) {

		Map<Id, List<AddFee2Wrapper>> returnMap = new Map<Id, List<AddFee2Wrapper>> ();
		Map<String, EPPS_Fee__mdt> feeMap = EPPSHelperMethods.getFeesByLabel();

		for (Payment_Schedule_Item__c psi : psiList) {

			List<AddFee2Wrapper> addWrapperList = new List<AddFee2Wrapper>();

			// loop through child fee/settlement records
			for (Payment_Fee__c pf : psi.Payment_Fees__r) {

				AddFee2Wrapper addWrapper = new AddFee2Wrapper();
				// TODO what if the metadata is missing for a fee type? or fee type not specified, maybe trap null at query
				
				// this fee type details
				EPPS_Fee__mdt feeDetails = feeMap.get(pf.Type__c);

				if (feeDetails.Send_to_EPPS__c) {

					EPPSHelperMethods.Fee_Wrapper fee = new EPPSHelperMethods.Fee_Wrapper();

					fee.CardHolderID = psi.Payment_Plan__r.Opportunity__r.Account.EPPS_Id__c;	
					fee.FeeDate = DateTime.newInstance(psi.Payment_Date__c, Time.newInstance(0, 0, 0, 0));
					fee.FeeAmount = pf.Amount__c;
					fee.FeeType = pf.Type__c;
					fee.Description = feeDetails.Fee_Description__c;
					fee.PaidToName = feeDetails.PaidToName__c;
					fee.ContactName = feeDetails.PaidToContactName__c;
					fee.Description = feeDetails.Fee_Description__c;

					addWrapper.feeWrapper = fee;
					addWrapper.feeSettlementId = pf.Id;
					addWrapperList.add(addWrapper);
				}
			}

			returnMap.put(psi.Id, addWrapperList);
		}
		return returnMap;
	}

	public class AddFee2Wrapper {

		public EPPSHelperMethods.Fee_Wrapper feeWrapper;
		public String feeIdField;
		public String statusField;
		public Id feeSettlementId;
	}
}