force-app/main/default/objects/Payment_Fee__c/Payment_Fee__c.object-meta.xml
<CustomObject>
    <description>Payment fees associated with Payment Schedule Items</description>
    <label>Payment Fee</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Payment Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Fee__c/fields/Fee_Id__c.field-meta.xml
<CustomField>
    <fullName>Fee_Id__c</fullName>
    <label>Fee Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Banking Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Program Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Setup Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Payee Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Wire Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Wire Received Fee</fullName>
    </customValue>
    <description>Types of payment fees for Payment_Fee__c records</description>
    <masterLabel>Payment Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EPPSPaymentFeeStatusBatch.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : EPPSPaymentFeeStatusBatch
 * Author          : Shell Black (Sean Fawcett)
 * Created Date    : Jan 27, 2026
 * Last Modified By:
 * Last Modified On: Jan 27, 2026
 * Description     : Batch class to find payment fees and update their status.
 *					 This class should not be scheduled.  It is ran when the 	
 *					 Settelement status batch completes.
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Jan 27, 2026  │ Sean Fawcett │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
public class EPPSPaymentFeeStatusBatch implements Database.Batchable<SObject>, Database.AllowsCallouts 
{

    public Database.QueryLocator start(Database.BatchableContext bc) {

        Date targetDate = EPPSHelperMethods.getDateAfterBusinessDays(2);

        return Database.getQueryLocator([SELECT Id,
										Amount__c,
										Fee_Id__c,
										Name,
										Status_Code__c,
										Transaction_Id__c,
										Type__c
										FROM Payment_Fee__c
										WHERE Transaction_Id__c = null
										AND Fee_Id__c != null
										]);
    }

	//  Method executed per batch of records.
    public void execute(Database.BatchableContext bc, List<Payment_Fee__c> scope) 
	{
		for (Payment_Fee__c item : scope)
		{		
			item =  CalloutAndPopulateFields(item);			
		}

		Database.update(scope);

		IntegrationLogUtil.flush();
	}
	
	public Payment_Fee__c CalloutAndPopulateFields(Payment_Fee__c item)
	{
		try
		{
			EPPSHelperMethods.FindFee_Wrapper itemWrapper = new	EPPSHelperMethods.FindFee_Wrapper();							

			itemWrapper.FeeID = item.Fee_Id__c;
			
			// Callout to EPPS
			EPPSHelperMethods.EPPSResponse response = EPPSIntegrationMethodsEnhanced.findFeeById(itemWrapper);

			if (response.success) 
			{			
                if (response.FoundFees.containsKey(item.Fee_Id__c) == false)
                {
                    return item;  //  can happen if the fee being polled does not exist in EPPS
                }
                
				EPPSHelperMethods.FindFee_Wrapper wrapper = response.FoundFees.get(item.Fee_Id__c);

				item.Transaction_Id__c = EPPSHelperMethods.safeString(wrapper.EftTransactionID);
				item.Status_Code__c = EPPSHelperMethods.safeString(wrapper.StatusCode);
			
				//item.Status_Date__c = EPPSHelperMethods.safeDate(wrapper.StatusDate);				
				
				IntegrationLogUtil.createLog(
				IntegrationLogUtil.logBuilder()
				.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
				.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
				.method('findFeeById')
				.request(response.SOAPRequestBody)
				.response(response.SOAPResponseBody)
				.httpCode(response.HTTPResponseCode)
				.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
				.build());

				}
				else
				{
					IntegrationLogUtil.createLog(
					IntegrationLogUtil.logBuilder()
					.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
					.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
					.method('findFeeById')
					.request(response.SOAPRequestBody)
					.response(response.SOAPResponseBody)
					.httpCode(response.HTTPResponseCode)
					.status(response.Success ? IntegrationLogUtil.LogStatus.Success : IntegrationLogUtil.LogStatus.Failure)
					.build());
				}
		}
		catch (Exception e)
		{
			IntegrationLogUtil.createLog(
			IntegrationLogUtil.logBuilder()
			.settings(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT)
			.objectMeta(EPPSHelperMethods.EPPS_INTEGRATION_OBJ_MDT)
			.method('findFeeById')
			.exceptionMsg(EPPSHelperMethods.getExceptionDetails(e))
			.status(IntegrationLogUtil.LogStatus.Failure)
			.build());
		}
		return item;
	}

    public void finish(Database.BatchableContext bc) 
	{
		
		if (!Test.isRunningTest()) {
			Map<String, Object> settings = IntegrationLogUtil.getMetadataFieldValues(EPPSHelperMethods.EPPS_INTEGRATION_SETTING_MDT);
			Integer batchSize = Integer.valueOf(settings.get('Batch_Size_for_Client_Payment_Batch__c'));
			Database.executeBatch(new EPPSClientPaymentBatch(), batchSize);
		}
    }
}